In [1]:
using Pkg
using NPZ
using LinearAlgebra

In [2]:
main_path = "/home/sying/Documents/WordNetEmbeddings/data/output_140219_all/"

"/home/sying/Documents/WordNetEmbeddings/data/output_140219_all/"

In [3]:
p_matrix = npzread(string(main_path, "p_matrix.npy"))
p_matrix = convert(Array{Float32,2}, p_matrix) # BLAS function

56665×56665 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [4]:
axpy!(0.00001, Diagonal(rand(Float32, 56665) .- 0.5), p_matrix)

56665×56665 Array{Float32,2}:
 -3.0405e-7  0.0          0.0         0.0         …   0.0         0.0       
  0.0        4.72949e-6   0.0         0.0             0.0         0.0       
  0.0        0.0         -3.37467e-6  0.0             0.0         0.0       
  0.0        0.0          0.0         3.36518e-6      0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0         …   0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0         …   0.0         0.0       
  0.0        0.0          0.0         0.0             0.0         0.0       
  0.0        0.0          0.0         0.0     

In [5]:
lmul!(-0.75, p_matrix)
p_matrix += I

56665×56665 Array{Float32,2}:
  1.0  -0.0       -0.0  -0.0       -0.0       …  -0.0  -0.0  -0.0  -0.0     
 -0.0   0.999996  -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0        1.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0   0.999997  -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0        0.999997     -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0       …  -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0       …  -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0          -0.0  -0.0  -0.0  -0.0     
 -0.0  -0.0       -0.0  -0.0       -0.0       

In [ ]:
res = inv(p_matrix)

In [9]:
p_matrix = nothing

In [7]:
npzwrite(string(main_path, "random_walk.npy"), res)

In [8]:
npzwrite(string(main_path, "random_walk2.npy"), res)

In [ ]:

for i in range(dim[0] - 1):
    if np.random.rand() > .5:
        p_matrix[i, i] += random.uniform(0, 0.00001)
    else:
        p_matrix[i, i] -= random.uniform(0, 0.00001)

In [33]:
alpha = 0.75
G_last = Matrix{Float32}(I, 56665, 56665)

56665×56665 Array{Float32,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [32]:
iter = 50
alp_itr = alpha
p_matrix_itr = deepcopy(p_matrix)

56665×56665 Array{Float32,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [29]:
tmp = [[1 2]; [3 4]]

2×2 Array{Int64,2}:
 1  2
 3  4

In [35]:
G_last = nothing

In [24]:
tmp = 1

1

In [ ]:
for i = 1:iter
    axpy!(alp_itr, p_matrix_itr, G_last)
    alp_itr *= alpha
    
    println(string("Interation", i))
end

In [9]:
Base.summarysize(p_matrix)

6421844490

In [ ]:
pbar = ProgressBar(widgets=[Percentage(), Bar()], maxval=int(iter))
for i in pbar(range(int(iter))):
    s = time.time()
    g_rw = alp_itr * p_matrix_itr + G_last
    G_last = g_rw
    alp_itr *= alpha
    p_matrix_itr = np.dot(p_matrix_itr, p_matrix)
    f = time.time()
    print("iteration %d takes %s seconds" %(i+1,str(round(f-s))))


N/A%|                                                                         |